### ISSUE TITLE
Taskbar icon doesn't update to show unread messages

### ISSUE THREAD

**Issue by NickHam13** [smartfrigde/armcord#399]
**Describe the bug**
Title. I know it's a dupe of #375 but hopefully a new issue with more specific info can help.

**Screenshots**
![image](https://github.com/ArmCord/ArmCord/assets/49380508/f7553e28-547a-43a0-8563-c50e35df078f)
![image](https://github.com/ArmCord/ArmCord/assets/49380508/f55b3113-91e7-44e8-8f1b-92bb722a37bf)

**Desktop (please complete the following information):**
Windows 10, .exe install, 3.2.0 (bug was also present on 3.1.7)

**Comment by smartfrigde** [comment]
Fixed [in this commit](https://github.com/ArmCord/ArmCord/commit/6d491437e405173d32027a741b4ebce4ecd3125a)

**Comment by NickHam13** [comment]
Still not working as intended after building from latest commit

**Comment by smartfrigde** [comment]
Go into settings, scroll down until you see a copy debug info option. Send the output here

**Comment by NickHam13** [comment]
```
**OS:** win32 Windows 10 Enterprise
**Architecture:** ia32
**ArmCord version:** 3.2.0
**Electron version:** 24.3.0
`{
    "windowStyle": "default",
    "armcordCSP": true,
    "minimizeToTray": true,
    "startMinimized": false,
    "automaticPatches": true,
    "inviteWebsocket": true,
    "mobileMode": false,
    "alternativePaste": false,
    "disableAutogain": false,
    "dynamicIcon": true,
    "spellcheck": true,
    "channel": "stable",
    "mods": "vencord",
    "performanceMode": "performance",
    "trayIcon": "default",
    "skipSplash": false,
    "useLegacyCapturer": false,
    "doneSetup": true
}`
```

**Comment by smartfrigde** [comment]
Did you restart ArmCord completely after rebuilding?

**Comment by NickHam13** [comment]
Yes, I also tried restarting my PC

**Comment by NickHam13** [comment]
Any update on this? I feel that the issue should be reopened as it's not actually fixed for me, even after building from latest

**Comment by smartfrigde** [comment]
I'm unable to reproduce your issue, are you using any titlebar modifications like translucenttb?

**Comment by NickHam13** [comment]
Nope, nor am I using anything (to my knowledge) that could be messing with the icon. I still do think the issue should be reopened as it's not user error at this point and it's easier for people with the same issue to find, which could help in tracking down whatever's going on since you can't reproduce yourself. If you need any other info or logs, don't hesitate to let me know

**Comment by PinkSerenity** [comment]
I think it might have something to do with pinning it to taskbar. When I have ArmCord running in the background and get a notification, it will add the dynamic icon to the taskbar instead of creating an instance of the pinned non-dynamic icon. When I un-pin the existing icon and pin the new dynamic one, it will become the default static one.

**Comment by Xatha** [comment]
I can confirm the behaviour @Tojaw is describing also happens to me. If I pin ArmCord the dynamic icon will not be displayed and is instead swapped with the static default icon.

**Comment by Aria-NL** [comment]
I'm getting no dynamic icon with the icon unpinned and no taskbar mods. Win11 Pro, installed via Winget

**Comment by PinkSerenity** [comment]
> I'm getting no dynamic icon with the icon unpinned and no taskbar mods. Win11 Pro, installed via Winget

Winget likely installs the MS Store version which does not support dynamic icons. Try the version here instead.

**Comment by Aria-NL** [comment]
> > I'm getting no dynamic icon with the icon unpinned and no taskbar mods. Win11 Pro, installed via Winget
> 
> Winget likely installs the MS Store version which does not support dynamic icons. Try the version here instead.

Checked with Winget, and it's downloading the setup .exe from the latest release:
![image](https://github.com/ArmCord/ArmCord/assets/14789279/948a4982-6167-4b32-a62f-604fa7d4d3f7)

**Comment by PinkSerenity** [comment]
Is the dynamic tray icon unchecked? I don't know if that's still the case, but the two icons used to not be compatible. Also, do you have badges enabled in the Windows settings? I assume so, just making sure.

**Comment by Aria-NL** [comment]
Dynamic icon is toggled on in Armcord settings, unless there's another switch I need to flip too. Taskbar badges should be enabled.

**Comment by PinkSerenity** [comment]
Okay, I've been trying for 15 minutes to set my ArmCord settings to English, but unfortunately they appear to not be controlled by Discord's language settings. Anyway, the last entry should be one regarding the tray icon. That's the icon at the right side of the taskbar. Often it's hidden behind an arrow button thingy. I know that in past versions you had to set this to something static so that the dynamic taskbar icon works. Like White Plug or something. It's worth a try. Otherwise, I fear you have to wait for a collaborator.

**Comment by Aria-NL** [comment]
Looks like it's not working - I can see that the little window bar icon is dynamic, it's just the taskbar icon is not.

**Comment by PinkSerenity** [comment]
And if you switch it? If you make it non-dynamic? That's my last guess.

**Comment by Aria-NL** [comment]
No change unfortunately

**Comment by PinkSerenity** [comment]
Okay, then I unfortunately don't have any idea. Let's hope that a collaborator notices this thread.
Also, totally unrelated, I love your profile pic.

**Comment by smartfrigde** [comment]
@Aria-NL can you open ArmCord settings, scroll down and click on copy debug info button and send that here?

**Comment by Aria-NL** [comment]
yep, here you go:

**OS:** win32 Windows 10 Pro
**Architecture:** x64
**ArmCord version:** 3.2.3
**Electron version:** 25.4.0
{
    "windowStyle": "transparent",
    "channel": "stable",
    "armcordCSP": true,
    "minimizeToTray": true,
    "automaticPatches": false,
    "keybinds": [],
    "alternativePaste": false,
    "mods": "vencord",
    "spellcheck": true,
    "performanceMode": "none",
    "skipSplash": true,
    "inviteWebsocket": true,
    "startMinimized": false,
    "dynamicIcon": true,
    "tray": true,
    "customJsBundle": "https://armcord.app/placeholder.js",
    "customCssBundle": "https://armcord.app/placeholder.css",
    "disableAutogain": false,
    "useLegacyCapturer": false,
    "mobileMode": false,
    "trayIcon": "default",
    "doneSetup": true,
    "clientName": "ArmCord",
    "customIcon": "C:\\Users\\Aria\\AppData\\Local\\ArmCord\\resources\\app.asar\\assets\\desktop.png"
}

**Comment by Aria-NL** [comment]
![image](https://github.com/ArmCord/ArmCord/assets/14789279/de5a7d3f-4331-4c85-b3be-14d4cd23519e)

**Comment by mfsoup** [comment]
Doesn't work for me either on 3.2.4. 

**OS:** win32 Windows 10 Pro
**Architecture:** x64
**ArmCord version:** 3.2.4
**Electron version:** 26.1.0
`{
    "windowStyle": "default",
    "channel": "stable",
    "armcordCSP": true,
    "minimizeToTray": true,
    "automaticPatches": false,
    "keybinds": [],
    "alternativePaste": false,
    "mods": "vencord",
    "spellcheck": true,
    "performanceMode": "performance",
    "skipSplash": false,
    "inviteWebsocket": true,
    "startMinimized": false,
    "dynamicIcon": true,
    "tray": true,
    "customJsBundle": "https://armcord.app/placeholder.js",
    "customCssBundle": "https://armcord.app/placeholder.css",
    "disableAutogain": false,
    "useLegacyCapturer": false,
    "mobileMode": false,
    "trayIcon": "default",
    "doneSetup": true,
    "clientName": "ArmCord",
    "customIcon": "C:\\Users\\Moo\\AppData\\Local\\ArmCord\\resources\\app.asar\\assets\\desktop.png",
    "multiInstance": false
}`

**Comment by smt923** [comment]
I can confirm specifically the pinned icon vs unpinned icon behaviour, from the non-MS store release exe and directly downloading at least, fairly easy to do a repeatable thing where you have a notification and just pin and unpin, you can see it change from having the red number to not, the tray icon always has the notification dot for me for what it's worth, it would be nice to be able to get the dot while pinned as I imagine is intended, but at least for me I can live with it being unpinned to get the notification icon

I tried to test the windows store version (3.3.0) however it seems to not have the taskbar notification setting anymore, and pinning or unpinning didn't change anything

also not sure if it's supposed to 'revert' to the old icon for the notification dot after pinning and unpinning or if it's meant to be the armcord icon, but that seems to change too

Unpinned:
![image](https://github.com/ArmCord/ArmCord/assets/3849041/4ef8b709-4095-4533-8839-5f336227ab60)
Pinned:
![image](https://github.com/ArmCord/ArmCord/assets/3849041/1b9b78c6-72d9-4392-a54c-28ec3c30931e)

**OS:** win32 Windows 10 Pro
**Architecture:** x64
**ArmCord version:** 3.2.5
**Electron version:** 27.0.2
`{
    "windowStyle": "default",
    "channel": "stable",
    "armcordCSP": true,
    "minimizeToTray": true,
    "automaticPatches": true,
    "keybinds": [],
    "alternativePaste": false,
    "multiInstance": false,
    "mods": "vencord",
    "spellcheck": true,
    "performanceMode": "performance",
    "skipSplash": false,
    "inviteWebsocket": true,
    "startMinimized": false,
    "dynamicIcon": true,
    "tray": true,
    "customJsBundle": "https://armcord.app/placeholder.js",
    "customCssBundle": "https://armcord.app/placeholder.css",
    "disableAutogain": false,
    "useLegacyCapturer": false,
    "mobileMode": false,
    "trayIcon": "default",
    "doneSetup": true,
    "clientName": "ArmCord",
    "customIcon": "C:\\Users\\smt\\AppData\\Local\\ArmCord\\resources\\app.asar\\assets\\desktop.png"
}`

**Comment by gospodzverina** [comment]
did anyone find a way to fix this?

**Comment by smartfrigde** [comment]
Can you try latest devbuild? I've changed the way ping count is applied to the icon (it's more similar to how the official Discord app handles it), make sure dynamic icon is disabled in settings (yes confusing I know, will be resolved when hits stable)

https://github.com/ArmCord/ArmCord/releases/tag/devbuild

**Comment by smartfrigde** [comment]
This is fixed on devbuilds
