### ISSUE TITLE
Titlebar doesn't always inject

### ISSUE THREAD

**Issue by smartfrigde** [smartfrigde/armcord#700]
**Describe the bug**
~~When running on low-end machines~~ ArmCord titlebar simply doesn't inject with no errors in the console. It's not present in the dom tree either. However the [`custom-titlebar` property is set](https://github.com/ArmCord/ArmCord/blob/dev/src/discord/preload/titlebar.mts#L36). Could be a timing issue?
**To Reproduce**

Run ArmCord on low-end 2 core cpu with 2GB's of ram on Linux/Windows 🚎 

**Expected behavior**
Custom titlebar should be present 

**Desktop (please complete the following information):**
 - OS: reports from Windows and Linux users

**Additional context**
Possibly adding a check for a titlebar after certain period of time would solve this.

**Comment by EsaiTheMartian2007** [comment]
Same here, This bug has to be fixed

**Comment by WindClan** [comment]
This happened on my not that low end dualcore laptop (but only 4gb of ram so makes sense) 
It started after the newest armcord update for me

**Comment by smartfrigde** [comment]
Can you provide full logs of running ArmCord from the terminal and send any errors (red), warnings (yellow) from the developer console (CTRL+SHIFT+I --> Console)? I'm having hard time reproducing this on my end, I've tried various machines and OS'es

**Comment by Cyborgnetical** [comment]
This?
`
[FAST CONNECT] wss://gateway.discord.gg/?encoding=json&v=9&compress=zlib-stream, encoding: json, version: 9
VM129:14 shelter shelter is initializing...
VencordWeb:5  Vencord   PluginManager  Starting plugins (stage Init)
VencordWeb:5  Vencord   PluginManager  Starting plugin NoTrack
preload.mjs:41 ArmCord 3.3.0
 [FAST CONNECT] connected in 261ms
VencordWeb:5  Vencord   WebpackInterceptor  Found Webpack module factory web.ec335eb65865a8777673.js
VencordWeb:5  Vencord   WebpackInterceptor  Main Webpack found in web.ec335eb65865a8777673.js, initializing internal references to WebpackRequire
VencordWeb:5  Vencord   WebpackInterceptor  Patching webpackChunkdiscord_app.push
web.ec335eb65865a8777673.js:12 [ProcessUtilsElectron] setMemoryInformation not available.
web.ec335eb65865a8777673.js:12 [default] [BUILD INFO] Release Channel: stable, Build Number: 325182, Version Hash: 6e34e46bfbfacdc17343460dc5b1b29530d75ea9
web.ec335eb65865a8777673.js:12 AppCrashedFatalReport: getLastCrash not supported.
VencordWeb:5  Vencord   NoTrack  Disabling Sentry by erroring its WebpackInstance
VencordWeb:25 Uncaught Error: Sentry successfully disabled
    at Function.set (VencordWeb:25:17446)
    at sentry.975ac4a3d7d10f56cc57.js:453:37896
    at sentry.975ac4a3d7d10f56cc57.js:453:38435
VencordWeb:5  Vencord   PluginManager  Starting plugins (stage DOMContentLoaded)
armcord-settings:223 Proxy(Object)
VM129:14 shelter ArmCord Settings
VM129:14 shelter shelter is initialized. took: 1971.8ms
web.ec335eb65865a8777673.js:12 [DEPRECATED] Please use `subscribeWithSelector` middleware
a @ web.ec335eb65865a8777673.js:12
web.ec335eb65865a8777673.js:12 [GatewaySocket] [CONNECT] wss://gateway.discord.gg, encoding: json, version: 9, compression: zlib-stream
web.ec335eb65865a8777673.js:12 [GatewaySocket] [FAST CONNECT] successfully took over websocket, state: Object
web.ec335eb65865a8777673.js:12 [GatewaySocket] [CONNECTED] wss://gateway.discord.gg/?encoding=json&v=9&compress=zlib-stream in 0 ms
web.ec335eb65865a8777673.js:12 [GatewaySocket] [READY] took 761ms, as e6f82752b73e47e9a20d339e64c2f896
web.ec335eb65865a8777673.js:12 [Flux] Dispatching CONNECTION_OPEN
web.ec335eb65865a8777673.js:12 [DatabaseManager] removing database (user: 758848116593786892, database: undefined)
VencordWeb:5  Vencord   PluginManager  Starting plugins (stage WebpackReady)
VencordWeb:5  Vencord   PluginManager  Starting plugin BadgeAPI
VencordWeb:5  Vencord   PluginManager  Starting plugin SupportHelper
VencordWeb:5  Vencord   PluginManager  Starting plugin WebContextMenus
VencordWeb:5  Vencord   PluginManager  Starting plugin WebKeybinds
web.ec335eb65865a8777673.js:12 [GatewaySocket] [READY_SUPPLEMENTAL] took 820ms
/api/v9/users/@me/affinities/v2/users:1 
        
        
       Failed to load resource: the server responded with a status of 401 ()
web.ec335eb65865a8777673.js:12 [MessageActionCreators] Fetching messages for 1260074144502906994 between undefined and undefined. jump={"jumpType":"ANIMATED"}
web.ec335eb65865a8777673.js:12 [MessageActionCreators] Fetched 50 messages for 1260074144502906994 isBefore:false isAfter:false
web.ec335eb65865a8777673.js:12 [ChannelMessages] loadComplete: resetting state for channelId=1260074144502906994, sending.length=0
/api/v9/users/@me/affinities/v2/users:1 
        
        
       Failed to load resource: the server responded with a status of 401 ()
preload.mjs:27 armcord-settings: armcord://plugins/armcordSettings/
preload.mjs:41 Plugin armcord-settings already injected
preload.mjs:27 armcord-screenshare: armcord://plugins/screenshareQualityFix/
preload.mjs:41 Plugin armcord-screenshare already injected
VM319:6 Starting RPC Bridge
/api/v9/users/@me/billing/user-offer:1 
        
        
       Failed to load resource: the server responded with a status of 404 ()
54The resource <URL> was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate `as` value and it is preloaded intentionally.
web.ec335eb65865a8777673.js:12 [discord_protos.discord_users.v1.FrecencyUserSettings] Loading proto
web.ec335eb65865a8777673.js:12 [DEPRECATED] Please use `subscribeWithSelector` middleware
a @ web.ec335eb65865a8777673.js:12
web.ec335eb65865a8777673.js:12 [MessageQueue] Queueing message to be sent LogId:8132
web.ec335eb65865a8777673.js:12 [MessageQueue] Draining message from queue LogId:8132 QueueLength: 0
web.ec335eb65865a8777673.js:12 [MessageQueue] Draining Message Queue with:  0
web.ec335eb65865a8777673.js:12 [MessageQueue] Finished draining message from queue LogId:8132 QueueLength: 0
web.ec335eb65865a8777673.js:12 [ComponentDispatchUtils] ComponentDispatch.subscribe: Attempting to add a duplicate listener POPOUT_CLOSE
(anonymous) @ web.ec335eb65865a8777673.js:12
web.ec335eb65865a8777673.js:12 [WindowVisibilityVideoManager] Window visibility incoming video changed, incomingVideoEnabled = false
web.ec335eb65865a8777673.js:12 [WindowVisibilityVideoManager] Window visibility incoming video changed, incomingVideoEnabled = true
web.ec335eb65865a8777673.js:12 [MessageActionCreators] Fetching messages for 1276227504243474546 between undefined and undefined. jump={"jumpType":"ANIMATED"}
web.ec335eb65865a8777673.js:12 [MessageActionCreators] Fetched 50 messages for 1276227504243474546 isBefore:false isAfter:false
web.ec335eb65865a8777673.js:12 [ChannelMessages] loadComplete: resetting state for channelId=1276227504243474546, sending.length=0
/api/v9/users/@me/affinities/v2/users:1 
        
        
       Failed to load resource: the server responded with a status of 401 ()
42Third-party cookie will be blocked in future Chrome versions as part of Privacy Sandbox.
web.ec335eb65865a8777673.js:12 Hold Up!
web.ec335eb65865a8777673.js:12 If someone told you to copy/paste something here you have an 11/10 chance you're being scammed.
web.ec335eb65865a8777673.js:12 Pasting anything in here could give attackers access to your Discord account.
web.ec335eb65865a8777673.js:12 Hold Up!
web.ec335eb65865a8777673.js:12 If someone told you to copy/paste something here you have an 11/10 chance you're being scammed.
web.ec335eb65865a8777673.js:12 Pasting anything in here could give attackers access to your Discord account.
web.ec335eb65865a8777673.js:12 Hold Up!
web.ec335eb65865a8777673.js:12 If someone told you to copy/paste something here you have an 11/10 chance you're being scammed.
web.ec335eb65865a8777673.js:12 Pasting anything in here could give attackers access to your Discord account.
web.ec335eb65865a8777673.js:12 Hold Up!
web.ec335eb65865a8777673.js:12 If someone told you to copy/paste something here you have an 11/10 chance you're being scammed.
web.ec335eb65865a8777673.js:12 Pasting anything in here could give attackers access to your Discord account.
web.ec335eb65865a8777673.js:12 Hold Up!
web.ec335eb65865a8777673.js:12 If someone told you to copy/paste something here you have an 11/10 chance you're being scammed.
web.ec335eb65865a8777673.js:12 Pasting anything in here could give attackers access to your Discord account.
web.ec335eb65865a8777673.js:12 Unless you understand exactly what you are doing, close this window and stay safe.
web.ec335eb65865a8777673.js:12 If you do understand exactly what you are doing, you should come work with us https://discord.com/jobs
`

**Comment by Darkextratoasty** [comment]
Same issue here:
- flatpak install from "Software" app
- Fedora 40
- Gnome 46.4
- Intel 1340P
- 32GB RAM

Running `flatpak run xyz.armcord.ArmCord` yields:
```
Using Wayland, enabling PipeWire for video capture.
Screenshare may be broken on first start.
Make sure you have the legacy screencapturer enabled.
Wayland socket not available, running through Xwayland.
Passing the following arguments to Electron: --enable-gpu-rasterization --enable-zero-copy --enable-gpu-compositing --enable-native-gpu-memory-buffers --enable-oop-rasterization --disable-gpu-blocklist --enable-features=UseSkiaRenderer,WebRTCPipeWireCapturer,WebRTCPipeWireCapturer
[3:0908/011606.835845:ERROR:bus.cc(407)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
Wayland detected, using PipeWire for video capture.
ArmCord has been run before. Skipping setup.
Config is fine
Window config is fine
No performance modes set
Downloading Shelter
Downloading Vencord
[Config Manager] Current config: {
    "windowStyle": "default",
    "channel": "stable",
    "armcordCSP": true,
    "minimizeToTray": false,
    "keybinds": [],
    "multiInstance": false,
    "mods": "vencord",
    "spellcheck": true,
    "hardwareAcceleration": true,
    "performanceMode": "none",
    "skipSplash": false,
    "inviteWebsocket": false,
    "startMinimized": false,
    "dynamicIcon": false,
    "tray": true,
    "customJsBundle": "https://armcord.app/placeholder.js",
    "customCssBundle": "https://armcord.app/placeholder.css",
    "disableAutogain": false,
    "useLegacyCapturer": false,
    "mobileMode": false,
    "trayIcon": "default",
    "doneSetup": true,
    "clientName": "ArmCord",
    "customIcon": "/app/bin/armcord/resources/app.asar/assets/desktop.png",
    "smoothScroll": true,
    "autoScroll": false
}
Gtk-Message: 01:16:07.952: Failed to load module "canberra-gtk-module"
Gtk-Message: 01:16:07.952: Failed to load module "pk-gtk-module"
Gtk-Message: 01:16:07.952: Failed to load module "canberra-gtk-module"
Gtk-Message: 01:16:07.952: Failed to load module "pk-gtk-module"
[3:0908/011607.961951:ERROR:bus.cc(407)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
[3:0908/011607.961997:ERROR:bus.cc(407)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
Setting up CSP unrestricter...
[Window state manager] {"width":1182,"height":833,"isMaximized":false,"x":542,"y":162}
[Window state manager] {"width":1182,"height":833,"isMaximized":false,"x":542,"y":162}
[Window state manager] {"width":1182,"height":833,"isMaximized":false,"x":542,"y":162}
[Window state manager] {"width":1182,"height":833,"isMaximized":false,"x":542,"y":162}
[Window state manager] {"width":1182,"height":833,"isMaximized":false,"x":542,"y":162}
Starting screenshare module...
[Theme Manager] Loaded Quick CSS
/app/bin/armcord/resources/app.asar/ts-out/assets/app/Loading.webm
[97:0908/011609.681550:ERROR:ffmpeg_common.cc(965)] Unsupported pixel format: -1
/app/bin/armcord/resources/app.asar/ts-out/assets/app/Update.webp
[109:0908/011610.676115:ERROR:ffmpeg_common.cc(965)] Unsupported pixel format: -1
[52:0908/011612.916332:ERROR:gl_surface_presentation_helper.cc(260)] GetVSyncParametersIfAvailable() failed for 1 times!
[52:0908/011612.972863:ERROR:gl_surface_presentation_helper.cc(260)] GetVSyncParametersIfAvailable() failed for 2 times!
[52:0908/011618.118187:ERROR:gl_surface_presentation_helper.cc(260)] GetVSyncParametersIfAvailable() failed for 3 times!
[3:0908/012138.563277:ERROR:CONSOLE(1)] "Request Autofill.enable failed. {"code":-32601,"message":"'Autofill.enable' wasn't found"}", source: devtools://devtools/bundled/core/protocol_client/protocol_client.js (1)
[3:0908/012138.563332:ERROR:CONSOLE(1)] "Request Autofill.setAddresses failed. {"code":-32601,"message":"'Autofill.setAddresses' wasn't found"}", source: devtools://devtools/bundled/core/protocol_client/protocol_client.js (1)
```
Notes on message:
`Failed to load module "canberra-gtk-module"`: libcanberra-gtk3 is installed and up to date.
`Failed to load module "pk-gtk-module"`:  PackageKit-gtk3-module is installed and up to date.
`Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory`: that file does exist.

Opening the dev console in ArmCord:
Error:
```
Uncaught Error: Sentry successfully disabled
    at Function.set (VencordWeb:25:17446)
    at sentry.975ac4a3d7d10f56cc57.js:453:37896
    at sentry.975ac4a3d7d10f56cc57.js:453:38435
```
Warning:
```
[DEPRECATED] Please use `subscribeWithSelector` middleware
```
Error:
```
/api/v9/users/@me/affinities/v2/users:1 
       Failed to load resource: the server responded with a status of 401 ()
```
Error:
```
api.spotify.com/v1/me/player?additional_types=track%2Cepisode:1
       Failed to load resource: the server responded with a status of 401 ()
```
Error:
```
/api/v9/users/@me/connections/spotify/************/access-token:1
       Failed to load resource: the server responded with a status of 401 ()
```
Warning (there are 24 entries here, I can paste the full list if needed):
```
The resource <URL> was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate `as` value and it is preloaded intentionally.
```

I also see `Open issues to view 3 issues: 3 breaking changes`, all three are `depreciated feature used`.
```
StorageType.persistent is deprecated. Please use standardized navigator.storage instead.

Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check https://xhr.spec.whatwg.org/.

Unload event listeners are deprecated and will be removed.
```

@smartfrigde please let me know if I can provide more details.

**Comment by huntyh** [comment]
Same here. I'm also on an old netbook with 2 gigs of ram and an old intel atom. No titlebar for some reason, I can't see any related errors in the console either.

**Comment by WindClan** [comment]
Even more confused, just happened on my main desktop which is the opposite of low end

**Comment by smartfrigde** [comment]
https://github.com/ArmCord/ArmCord/commit/74b78fd61adb83cc42eb8f81ee2d6743bbce7040

Fixed here, you can test with [our devbuilds](https://github.com/ArmCord/ArmCord/releases/tag/devbuild)

**Comment by TophC7** [comment]
I am currently trying the devbuild and the "custom" tittle bar is still not working.
Legcord opens with NO tittle bar then force restarts with native tittle bar.  Cant make it use the custom one at all.

Im on arm64 win11
