### ISSUE TITLE
Blank screen upon installation

### ISSUE THREAD

**Issue by flexagoon** [smartfrigde/armcord#779]
**Describe the bug**
After installing the app and going through the setup wizard, I only see a blank screen

**To Reproduce**
1. Install the Flatpak
2. Complete the initial setup

**Expected behavior**
The app loads

**Screenshots**
![image](https://github.com/user-attachments/assets/d9978b9e-47b1-4ff9-b738-c5f1f9fe99a5)

**Desktop (please complete the following information):**
 - OS: Linux (Fedora 41)
 - Method of installation: Flatpak
 - Version: 3.3.1

**Comment by flexagoon** [comment]
Same thing happens with the appimage. I get the following error:

```
(node:85154) UnhandledPromiseRejectionWarning: TypeError: fetch failed
    at node:internal/deps/undici/undici:13185:13
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async ProcessServer.getDetectables (file:///tmp/.mount_LegcorRVDmN1/resources/app.asar/node_modules/arrpc/src/process/index.js:108:20)
(Use `legcord --trace-warnings ...` to show where the warning was created)
(node:85154) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
```

**Comment by flexagoon** [comment]
Re-launching the app a few times fixes the issue

**Comment by SomeAspy** [comment]
permanently? If you can't reproduce the issue anymore I don't have anything to go after
what is the output of the log when it hangs like this?

**Comment by etwodev** [comment]
Also having this issue. Upgraded from 1.0.5 to 1.0.6 recently after being fed up of being bugged to upgrade.
Fedora 41. Hyprland. Not much to say beyond "It randomly goes blank". No crash log, Session Storage logs give nothing.

**Comment by fzwoch** [comment]
Similar to #839 I think. Tried  deleting `.config/legcord` to start over. Let the first setup screen idling for a couple of seconds, after 30 seconds or so the window turns white. Tested with 1.1.0.

After screen turns white I tried to kill the process. It spit out the following errors:
```
[38120:0303/222005.572719:ERROR:zygote_communication_linux.cc(296)] Failed to send GetTerminationStatus message to zygote
[38120:0303/222005.588240:ERROR:network_service_instance_impl.cc(613)] Network service crashed, restarting service.
[38120:0303/222005.598683:ERROR:gpu_process_host.cc(975)] GPU process launch failed: error_code=1002
[38120:0303/222005.602422:ERROR:gpu_process_host.cc(975)] GPU process launch failed: error_code=1002
[38120:0303/222005.604889:ERROR:gpu_process_host.cc(975)] GPU process launch failed: error_code=1002
[38120:0303/222005.605515:ERROR:gpu_process_host.cc(975)] GPU process launch failed: error_code=1002
[38120:0303/222005.608813:ERROR:gpu_process_host.cc(975)] GPU process launch failed: error_code=1002
[38120:0303/222005.609445:ERROR:gpu_process_host.cc(975)] GPU process launch failed: error_code=1002
[38120:0303/222005.610139:ERROR:gpu_process_host.cc(975)] GPU process launch failed: error_code=1002
[38120:0303/222005.610464:ERROR:gpu_process_host.cc(975)] GPU process launch failed: error_code=1002
[38120:0303/222005.610875:ERROR:gpu_process_host.cc(975)] GPU process launch failed: error_code=1002
[38120:0303/222005.610939:FATAL:gpu_data_manager_impl_private.cc(423)] GPU process isn't usable. Goodbye.
Trace/breakpoint trap (core dumped)

```
but I guess these may be due to the kill signal?

**Comment by stectr** [comment]
Currently on Asahi Linux Fedora and also same issue. Same issue happens on Vesktop which makes me wonder if its not a specific Legcord problem.

**Comment by andymandias** [comment]
Seeing a similar issue, also on Asahi Linux Fedora.  Deleting `~/.config/legcord` brings back the setup screen, but after setting up my account the window goes blank after ~10 seconds.  Does not react to any user input as far as I can tell.  When relaunching the application after setup has already been completed the window is immediately blank (no ~10 seconds of working time as was available during initial setup).  Deleting the `~/.config/legcord/GPUCache` has no effect.

**Comment by smartfrigde** [comment]
Fixed in 1.1.1

**Comment by user-grinch** [comment]
Version 1.1.1, still occurs

![Image](https://github.com/user-attachments/assets/6455c8e8-cb64-484b-8afa-2025f3b44faa)

**Comment by Flamethr0wer** [comment]
I am also having this issue. Does anyone know of a solution?

**Comment by justicecurcian** [comment]
I also have this issue, but on windows 10

**Comment by etwodev** [comment]
> Version 1.1.1, still occurs
> 
> ![Image](https://github.com/user-attachments/assets/6455c8e8-cb64-484b-8afa-2025f3b44faa)

This looks like a different issue to the one in the MR.

**Comment by ZTetriminos** [comment]
Windows 10 x64, same issue. Updated Legcord, nothing changed. I had to delete AppData\Roaming\legcord for it to load again...

**Comment by jgoedde** [comment]
Same issue. But normal discord client is also not working for me, stuck on "Starting", with blank screen

**Comment by Ferrum115** [comment]
CachyOS Linux, hyprland (and xfce4). 
How to achieve: 
1) Install Ryoku shell for hyprland|default XFCE4
2) via pacman (using cachyos repos) install legcord or legcord-bin
3) launch it, it will go blank after finishing "loading" screen.

<img width="1256" height="1539" alt="Image" src="https://github.com/user-attachments/assets/720a461a-ca9d-44f8-aab0-b7bf75c34e0f" />
