### ISSUE TITLE
Audio breaks on Screenshare and Screenshare fails

### ISSUE THREAD

**Issue by CryptisMidnight** [smartfrigde/armcord#798]
When I use Screensharing with audio, Legcord errors. It doesn't stream and it stops detecting sound on mic and mutes all speakers. The mic shows up correctly in Legcord and is not muted, just doesn't broadcast till I close Legcord and reopen it. I can screenshare without audio, and it doesn't matter on screen or  application.

1. Activate 'Share your Screen'
2. Click "Yes" on the Screenshare audio window
3. Mic breaks, no stream, and all speakers are muted

Expected behavior
Stream with audio

Desktop
 - OS: openSUSE Tumbleweed Hyprland
 - Installed with .rpm package downloaded from Releases
 - Version 1.0.5

Errors I get from launching it from terminal and getting this issue
```sh
[30163:1206/073346.339372:ERROR:egl_dmabuf.cc(609)] Failed to record frame: Error creating EGLImage - EGL_BAD_MATCH
[30163:1206/073346.339387:ERROR:shared_screencast_stream.cc(951)] Dropping DMA-BUF modifier: 144115188488387331 and trying to renegotiate stream parameters
[30163:1206/073346.346410:ERROR:egl_dmabuf.cc(609)] Failed to record frame: Error creating EGLImage - EGL_BAD_MATCH
[30163:1206/073346.346432:ERROR:shared_screencast_stream.cc(951)] Dropping DMA-BUF modifier: 144115188488370947 and trying to renegotiate stream parameters
[30163:1206/073346.358272:ERROR:egl_dmabuf.cc(609)] Failed to record frame: Error creating EGLImage - EGL_BAD_MATCH
[30163:1206/073346.358293:ERROR:shared_screencast_stream.cc(951)] Dropping DMA-BUF modifier: 144115188488174339 and trying to renegotiate stream parameters
WebRTC Capturer detected, skipping window creation.
'loop->recurse > 0' failed at ../src/pipewire/thread-loop.c:425 pw_thread_loop_wait()
[30163:1206/073350.006088:ERROR:browser_main_loop.cc(279)] GLib-GObject: ../gobject/gsignal.c:2684: instance '0x27e402b77f40' has no handler with id '1762'
[30163:1206/073350.068999:ERROR:egl_dmabuf.cc(609)] Failed to record frame: Error creating EGLImage - EGL_BAD_MATCH
[30163:1206/073350.069012:ERROR:shared_screencast_stream.cc(951)] Dropping DMA-BUF modifier: 144115188488387331 and trying to renegotiate stream parameters
[30163:1206/073350.076197:ERROR:egl_dmabuf.cc(609)] Failed to record frame: Error creating EGLImage - EGL_BAD_MATCH
[30163:1206/073350.076209:ERROR:shared_screencast_stream.cc(951)] Dropping DMA-BUF modifier: 144115188488370947 and trying to renegotiate stream parameters
[30163:1206/073350.081214:ERROR:egl_dmabuf.cc(609)] Failed to record frame: Error creating EGLImage - EGL_BAD_MATCH
[30163:1206/073350.081223:ERROR:shared_screencast_stream.cc(951)] Dropping DMA-BUF modifier: 144115188488174339 and trying to renegotiate stream parameters```

**Comment by a-plastic-bag** [comment]
Same here on Fedora Linux 40, installed via RPM.

**Comment by ramide1** [comment]
Same on arch linux kde wayland

**Comment by cogumelodogit** [comment]
same on artix kde wayland

**Comment by noinline** [comment]
Same on ArchLinux {x11, bspwm, wireplumber};

**Comment by EduardoStarZ** [comment]
Same error on Arch Linux (x11, i3-gaps, pipewire), however, i get an error on terminal:

{
  frame: WebFrameMain {
    _events: [Object: null prototype] {},
    _eventsCount: 0
  },
  securityOrigin: 'https://discord.com/',
  userGesture: true,
  videoRequested: true,
  audioRequested: true
}
trying to import /usr/share/legcord/app.asar/dist/venmic-x64.node
Failed to import Venmic module Error: Cannot find module '/usr/share/legcord/app.asar/dist/venmic-x64.node'
Require stack:
- /usr/share/legcord/app.asar/ts-out/main-Dy_lruhE.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1232:15)
    at s._resolveFilename (node:electron/js2c/browser_init:2:124485)
    at Module._load (node:internal/modules/cjs/loader:1058:27)
    at c._load (node:electron/js2c/node_init:2:16955)
    at Module.require (node:internal/modules/cjs/loader:1318:19)
    at require (node:internal/modules/helpers:179:18)
    at Qt (file:///usr/share/legcord/app.asar/ts-out/main-Dy_lruhE.js:48:645)
    at G (file:///usr/share/legcord/app.asar/ts-out/main-Dy_lruhE.js:48:891)
    at file:///usr/share/legcord/app.asar/ts-out/main-Dy_lruhE.js:48:1376
    at WebContents.<anonymous> (node:electron/js2c/browser_init:2:87415) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/usr/share/legcord/app.asar/ts-out/main-Dy_lruhE.js' ]
}

**Comment by smartfrigde** [comment]
Should be fixed in 1.1.1

**Comment by EduardoStarZ** [comment]
Just did a quick test with 1.1.1 and the error still persists with every element previously mentioned, however, no error shows up now:

{
  frame: WebFrameMain {
    _events: [Object: null prototype] {},
    _eventsCount: 0
  },
  securityOrigin: 'https://discord.com/',
  userGesture: true,
  videoRequested: true,
  audioRequested: true
}
trying to import /usr/lib/legcord/resources/app.asar/dist/venmic-x64.node
Imported Venmic module. Is PipeWire being used?: true
[2025-03-17 14:08:45.517] [venmic] [info] [patchbay] (handle) found default metadata: 39
[2025-03-17 14:08:45.517] [venmic] [info] [patchbay] (meta_update) speaker name: "alsa_output.pci-0000_00_1b.0.analog-stereo"
[2025-03-17 14:08:45.518] [venmic] [info] [patchbay] (get) running venmic 6.1.0
Obtained Venmic module
ID: screen:373:0
Audio status: true
{ id: 'screen:373:0', name: 'Entire screen' }
