### ISSUE TITLE
Legcord 1.1.2 Blank screen

### ISSUE THREAD

**Issue by CatPieLeaf** [smartfrigde/armcord#905]
**Describe the bug**
after updating to 1.1.2, it doesn't show anything. i already tried resetting legcord data, uninstalling it, nothing works. 1.1.2 is just broken. 1.1.1 works fine

**Screenshots**

![Image](https://github.com/user-attachments/assets/f3af6997-200b-45d2-a65a-cc6b1d89a9f2)

**Desktop (please complete the following information):**
 - Windows 11 24H2

**Comment by Quarta-feira** [comment]
I'm also having this issue on win11. 
I can even click on servers, the mouse pointer changes to the little hand, but I have no GUI on the window.

**Comment by ShaX5** [comment]
I am another who has this issue of a blank window using **Legcord v1.1.2** on **Windows 11 24H2 (OS Build 26120.3941)**

Please Fix it, thank you :)

![Image](https://github.com/user-attachments/assets/03e243fd-bc4f-4b7f-8af4-2b9232c96d1a)

**Comment by ShaX5** [comment]
Just to add an update, I just grabbed Legcord v1.1.3 from the Actions tab and the issue of the blank window is fixed!

![Image](https://github.com/user-attachments/assets/22a9d4da-9257-4507-8197-70101664efbf)

**Comment by smartfrigde** [comment]
https://github.com/Legcord/Legcord/releases/tag/v1.1.3

**Comment by Laci556** [comment]
Hey! In case anyone else run into this: fresh install on Windows 11 still shows blank screen (v1.1.3, never installed Legcord on this machine before). Installing v1.1.1 first, then updating resolved it

**Comment by AktaneDev** [comment]
thank you! fixed on 1.1.3! for me

**Comment by ShaX5** [comment]
You don't have to install the older version and go through updating, you just need to use the Zip (portable) version of Legcord. Link:

[https://github.com/Legcord/Legcord/releases/download/v1.1.3/Legcord-1.1.3-win-x64.zip](url)

Just extract the files into a new folder, then put that folder in your documents folder or something (I have a dedicated Portal Apps folder in the root of my C drive I use for these situations) and then create a shortcut from the main EXE to place on the desktop/taskbar/start, etc.
